# Generated by Django 4.0 on 2021-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='present',
            name='offered_by',
            field=models.ManyToManyField(blank=True, related_name='offered_by_person', to='myapp.Person'),
        ),
    ]
